# Generated by Django 3.2.18 on 2023-10-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
                ('cholesterol', models.BooleanField()),
                ('gluc', models.BooleanField()),
                ('smoke', models.BooleanField()),
                ('alco', models.BooleanField()),
                ('active', models.BooleanField()),
                ('cardio', models.BooleanField()),
            ],
        ),
    ]
