# Generated by Django 3.2.18 on 2023-10-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(help_text='Age in days'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Nonbinary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(help_text='centimeters'),
        ),
    ]
